# SPDX-FileCopyrightText: 2024 Peter Magnusson <me@kmpm.se>
#
# SPDX-License-Identifier: CC0-1.0

name: Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Tidy code
      run: make tidy

    - name: Install tools
      run: make tools

    - name: Build with xcaddy
      run: make

    - name: audit code and check for REUSE compliance
      run: make audit reuse no-dirty
